apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dslagphi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dslagphi:c4dc679b11670cfb21bbcbabe3d2090b64a0077c@sha256:0b095386f88c5ba24be8c59ef0ff9f09c58f604e96aa266ec2d2de1ea6b7fbf3
          name: container-image
